apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: employee.erp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: employee-service
                port:
                  number: 8081
    - host: approval.erp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: approval-request-service
                port:
                  number: 8082
    - host: notification.erp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8084
    - host: processing.erp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: approval-processing-service
                port:
                  number: 8083
