apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - employee-service-deployment.yaml
  - approval-request-service-deployment.yaml
  - approval-processing-service-deployment.yaml
  - notification-service-deployment.yaml
  - ingress.yaml
