apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - employee-service.yaml
  - approval-request-service.yaml
  - approval-processing-service.yaml
  - notification-service.yaml
  - ingress.yaml
